Repository wecode-bootcamp-korea/45-backend-westagram-1, pull requests merged in 2023-04, with the labels that each got.

#7 [강종범] Assignment 1: Express API - 초기 환경 세팅
  jongbeom/.env.sample
  jongbeom/.gitignore
  jongbeom/app.js
  jongbeom/package-lock.json
  jongbeom/package.json
Labels: 멘토 리뷰 요청

#2 [오진석] Assignment 1: Express API - 초기 환경 세팅
  jinseok/.env.sample
  jinseok/.gitignore
  jinseok/.prettierrc
  jinseok/app.js
  jinseok/package-lock.json
  jinseok/package.json
Labels: 수정 요청

#13 [오진석] Assignment 2: Express API - 유저 회원가입 하기
  jinseok/app.js
  jinseok/db/migrations/20230418094835_create_users_table.sql
Labels: 완료

#10 [문승종] Assignment 1: Express API - 초기환경세팅
  seungjong/.env.sample
  seungjong/app.js
  seungjong/gitignore
  seungjong/package-lock.json
  seungjong/package.json
Labels: 완료

#17 [문승종] Assignment 2 : sign up
  seungjong/.env.sample
  seungjong/.gitignore
  seungjong/app.js
  seungjong/db/migrations/20230419060012_create_users_table.sql
  seungjong/package-lock.json
  seungjong/package.json
Labels: 멘토 리뷰 요청

#18 [오진석] Assignment 3, 4, 5: Express API - CRUD
  jinseok/app.js
  jinseok/db/migrations/20230419013034_create_posts_table.sql
  jinseok/db/migrations/20230419081847_modify_users_table.sql
  jinseok/db/migrations/20230419082344_modify_posts_table.sql
Labels: 멘토 리뷰 요청

#20 [문승종] Assignment 3,4,5, : Express ApI - (CRUD) (1)
  jinseok/app.js
  jinseok/db/migrations/20230419013034_create_posts_table.sql
  jinseok/db/migrations/20230419081847_modify_users_table.sql
  jinseok/db/migrations/20230419082344_modify_posts_table.sql
  seungjong/app.js
Labels: 수정 요청

#15 [윤해찬] Assignment 3, 4, 5: Express API - CRUD (1)
  haechan45th/app.js
  haechan45th/db/migrations/20230418110144_user_create_table.sql
  haechan45th/db/migrations/20230418110153_post_create_table.sql
Labels: 멘토 리뷰 요청

#22 [문승종] Assignment 3, 4, 5: Express Api - CRUD(1)
  seungjong/.env.sample
  seungjong/app.js
  seungjong/db/migrations/20230419064437_create_posts_table.sql
  seungjong/db/migrations/20230419084619_modify_posts_table.sql
Labels: 멘토 리뷰 요청

#21 [오진석] Assignment 6, 7, 8: Express API - CRUD (2)
  jinseok/app.js
  jinseok/db/migrations/20230419063700_create_likes_table.sql
  jinseok/db/migrations/20230420071612_modify_posts_table.sql
Labels: 멘토 리뷰 요청

#24 [윤해찬] Assignment 6 7, 8: Express Api - CRUD(2)
  haechan45th/app.js
  haechan45th/db/migrations/20230418090004_create_users_table.sql
  haechan45th/db/migrations/20230421013746_user_like_table.sql
Labels: 멘토 리뷰 요청

#23 [문승종] Assignment 6 7, 8: Express Api - CRUD(2)
  seungjong/app.js
  seungjong/db/migrations/20230421065047_create_likes_table.sql
  seungjong/package-lock.json
Labels: 멘토 리뷰 요청

#25 [오진석] Assignment 9: Project Layered Pattern 적용
  jinseok/app.js
  jinseok/controller/likeController.js
  jinseok/controller/postController.js
  jinseok/controller/userController.js
  jinseok/model/dataSource.js
  jinseok/model/likeDao.js
  jinseok/model/postDao.js
  jinseok/model/userDao.js
  jinseok/routes/index.js
  jinseok/routes/likeRouter.js
  jinseok/routes/postRouter.js
  jinseok/routes/userRouter.js
  jinseok/service/likeService.js
  jinseok/service/postService.js
  jinseok/service/userService.js
  jinseok/utils/validation-check.js
Labels: 멘토 리뷰 요청

#26 [윤해찬] Assignment 9: Project Layered Pattern 적용
  haechan45th/.gitignore
  haechan45th/app.js
  haechan45th/db/migrations/20230418110144_user_create_table.sql
  haechan45th/package-lock.json
  haechan45th/package.json
  haechan45th/src/controllers/likeController.js
  haechan45th/src/controllers/postController.js
  haechan45th/src/controllers/userController.js
  haechan45th/src/models/dataSource.js
  haechan45th/src/models/likeDao.js
  haechan45th/src/models/postDao.js
  haechan45th/src/models/userDao.js
  haechan45th/src/routes/index.js
  haechan45th/src/routes/likeRouter.js
  haechan45th/src/routes/postRouter.js
  haechan45th/src/routes/userRouter.js
  haechan45th/src/services/likeService.js
  haechan45th/src/services/postService.js
  haechan45th/src/services/userService.js
  haechan45th/src/utils/validation-check.js
Labels: 멘토 리뷰 요청

#27 [문승종] Assignment 9: Project Layered Pattern 적용
  seungjong/.gitignore
  seungjong/app.js
  seungjong/controllers/likeController.js
  seungjong/controllers/postController.js
  seungjong/controllers/userController.js
  seungjong/db/migrations/20230419084619_modify_posts_table.sql
  seungjong/db/migrations/20230421124413_create_users_table.sql
  seungjong/db/migrations/20230421124425_create_posts_table.sql
  seungjong/db/migrations/20230421124443_create_likes_table.sql
  seungjong/models/dataSource.js
  seungjong/models/likeDao.js
  seungjong/models/postDao.js
  seungjong/models/userDao.js
  seungjong/routes/index.js
  seungjong/routes/likeRouter.js
  seungjong/routes/postRouter.js
  seungjong/routes/userRouter.js
  seungjong/services/likeService.js
  seungjong/services/postService.js
  seungjong/services/userService.js
  seungjong/utils/validationCheck.js
Labels: 멘토 리뷰 요청

#29 [오진석] Assignment 1, 2, 3 : Authentication & Authorization 과제
  jinseok/.env.sample
  jinseok/controller/postController.js
  jinseok/controller/userController.js
  jinseok/middleware/auth.js
  jinseok/model/userDao.js
  jinseok/package-lock.json
  jinseok/package.json
  jinseok/routes/postRouter.js
  jinseok/routes/userRouter.js
  jinseok/service/userService.js
Labels: 리뷰 진행 중

#28 [윤해찬] Assignment 1, 2, 3 : Authentication & Authorization 과제
  haechan45th/src/controllers/likeController.js
  haechan45th/src/controllers/postController.js
  haechan45th/src/controllers/userController.js
  haechan45th/src/middleware/auth.js
  haechan45th/src/models/postDao.js
  haechan45th/src/models/userDao.js
  haechan45th/src/routes/index.js
  haechan45th/src/routes/likeRouter.js
  haechan45th/src/routes/postRouter.js
  haechan45th/src/routes/userRouter.js
  haechan45th/src/services/userService.js
Labels: 리뷰 진행 중

#30 [문승종] Assignment 1, 2, 3 : Authentication & Authorization 과제
  seungjong/.gitignore
  seungjong/.prettierrc
  seungjong/controllers/postController.js
  seungjong/controllers/userController.js
  seungjong/models/userDao.js
  seungjong/package-lock.json
  seungjong/package.json
  seungjong/routes/likeRouter.js
  seungjong/routes/postRouter.js
  seungjong/routes/userRouter.js
  seungjong/services/likeService.js
  seungjong/services/postService.js
  seungjong/services/userService.js
  seungjong/utils/authorization.js
  seungjong/utils/validationCheck.js
Labels: 완료
